### ISSUE TITLE
direction arrow should be rendered behind the symbol

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/signs#2]
<img width="190" alt="image" src="https://github.com/syncpoint/signs/assets/38359572/7aacb279-b970-4727-bdea-c836b2bb121f">

For equipments the direction arrow should be rendered behind the symbol.

**Comment by dehmer** [comment]
@ThomasHalwax I'm on it...

**Comment by dehmer** [comment]
@ThomasHalwax Are you sure about this requirement? For 2525 C/D, direction indicator is rendered over/before the icon.
Technically it would be possible to change this, but the arrow might be a little too short to be clearly recognizable.

<img width="132" alt="Screenshot 2023-11-15 at 17 10 33" 
src="https://github.com/syncpoint/signs/assets/322462/0ba5e9ee-5aa4-4e0d-a3b1-03eb9af05d27">

Peekaboo ;-)

**Comment by ThomasHalwax** [comment]
I'm afraid you are right. The direction of movement indicator is in front of the symbol. Apologies for my mistake!

**Comment by dehmer** [comment]
No problem!
It was nice to see, that the code is flexible enough to achieve this.

Closing.
