### ISSUE TITLE
Exercise flag causes extension of conditional bar

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/signs#3]
When a symbol is flagged as "exercise" this extends the bounding box that is used for calculation the length of the operational condition bar. Without the "X" flag the bar has the correct size.

<img width="250" alt="image" src="https://github.com/syncpoint/signs/assets/38359572/c04f2bca-6238-4f71-981d-2386b354eea0">

<img width="233" alt="image" src="https://github.com/syncpoint/signs/assets/38359572/a1814fb0-a168-4602-9b8e-90f971c27416">

**Comment by dehmer** [comment]
I'm on it. We should postpone upcoming release until this is fixed.

**Comment by dehmer** [comment]
Straight from the source (Beckman, old generator):
![Screenshot 2024-07-10 at 19 45 58](https://github.com/syncpoint/signs/assets/322462/5b7b9be3-78ba-4e6c-9c77-3ff2e04c6c10)

It is pretty crammed around exercise indicator. I try to offset the right text fields further to the right.

**Comment by dehmer** [comment]
![Screenshot 2024-07-10 at 19 51 55](https://github.com/syncpoint/signs/assets/322462/49eb6cc8-ec66-46f7-9ec4-6e17794b27ba)
@ThomasHalwax Sorry, the "right fields" already sit comfortably where they are. Condition bar and Exercise indicator must NOT contribute to same bbox. Tricky, but doable.

**Comment by dehmer** [comment]
Fixed.
